### PR TITLE
Now more forkable!

### PR DESCRIPTION
**Pull request by MPagel**
Generalized instructions, improved descriptions on how to use the repository, made links relative and generally made this a better repo :P

### CODE REVIEW

**Comment by holman** [comment]
Not sure you meant to send this against my repo.

**Comment by MPagel** [comment]
Yes I did. Your repo has a bunch of absolute links and doesn't show how an author can create feedback links within their main readme file (rather than using the GitHub navigation on the side, which may not be intuitive for end-users of any given package).

Although my version is not perfect, I find it to be a substantial general improvement over the original. Obviously, you are welcome to remove/alter that last link and re-personalize it (e.g. your twitter account). Would it be possible to instead push this to a non-master fork of yours so it doesn't overwrite your personalization, while still remaining as a resource to the community as a whole?

I know I'm coming off as a combination of an arrogant asshole and a GitHub n00b. However, I think that providing a common means of presenting an end-user friendly system to use the "issues" system for feedback would be beneficial to the GitHub community at large, and "feedback" seems a logical package name that people can adapt to this end.

**Comment by holman** [comment]
I can see that rationale, although this repo was designed for my needs instead. I'd rather keep that approach than make it overly generic.

**Comment by MPagel** [comment]
...in any case, I have since updated my general-use feedback repo, but won't bug you with another merge request

**Pull request closed without merging**
